export const surpriseMePrompts = [
    'A mesmerizing night sky over an ancient, enchanted forest',
    'The captivating aurora borealis painting the night sky above a tranquil lake',
    'An ethereal nightscape with floating lanterns illuminating the sky above an old village',
    'Breathtaking city lights of Tokyo with a majestic night sky backdrop',
    'A serene night sky with a blanket of twilight hues over the rolling countryside',
    'A magical night sky illuminating the ruins of a medieval castle',
    'The silhouette of a mysterious, abandoned ship against the hypnotic night sky',
    'An awe-inspiring night sky mirrored on the glassy surface of a still ocean',
    'The tranquil night sky creating an enchanting atmosphere over a quaint mountain village',
    'The dazzling colors of the night sky over the dancing fountains of Las Vegas',
    'A haunting night sky above the eerie landscape of a forgotten ghost town',
    'A fascinating night sky enveloping the ancient pyramids of Egypt',
    'An idyllic night sky creating a dreamlike ambiance over the tranquil waters of Venice',
    'A majestic night sky adorning the towering peaks of the Himalayas',
    'The thrilling night sky over a bustling carnival with rides and attractions',
    'A dramatic night sky casting its spell over the vast expanse of the Sahara Desert',
    'A tranquil night sky over the iconic Eiffel Tower in Paris',
    'An electrifying night sky above a roaring waterfall surrounded by lush forests',
    'The night sky weaving its magic over the romantic cityscape of Prague',
    'A whimsical night sky with floating islands and waterfalls in a fantasy world',
    'The timeless beauty of the night sky enveloping the ancient Colosseum in Rome',
    'A serene night sky over the peaceful rice terraces in Bali',
    'The entrancing night sky bringing to life the mythical creatures of an enchanted land',
    'An atmospheric night sky over the winding canals and bridges of Amsterdam',
    'A beguiling night sky overshadowing the enigmatic Moai statues of Easter Island',
    'The night sky casting an otherworldly glow over the haunting beauty of Antarctica',
    'A striking night sky over the cascading terraces of Pamukkale, Turkey',
    'The night sky unfolding its secrets over the mystical landscape of Machu Picchu',
    'A breathtakingly tranquil night sky enveloping the charming streets of Santorini',
    'The night sky shedding its ethereal light over the rugged beauty of the Scottish Highlands',
    'A night sky, vivid and alive, over the iconic Sydney Opera House',
    'An inspiring night sky glistening above a serene Japanese Zen garden',
    'The night sky, eloquent in its silence, above the solemnity of the Taj Mahal',
    'A night sky steeped in wonder, overlooking the mystical temples of Angkor Wat',
    'The awe-striking night sky as a canvas to the lively Rio de Janeiro Carnival',
    'An ancient, forgotten city under the spellbinding embrace of the night sky',
    'A quaint lighthouse standing tall against the mysterious allure of the night sky',
    'The night sky casting a reflective reverie over a secluded monastery in the mountains',
    'A bewitching night sky creating an alluring mosaic over the exotic markets of Marrakech',
    'The night sky, a symphony of shadows, over the ancient, labyrinthine streets of Jerusalem',
];
export const weatherData = {
    moon: [
        'new moon',
        'waxing crescent',
        'first quarter',
        'waxing gibbous',
        'full moon',
        'waning gibbous',
        'third quarter',
        'waning crescent',
    ],
    clody: ['slightly cloudy', 'partly cloudy', 'mostly cloudy', 'very cloudy'],
    fog: ['slightly foggy', 'moderately foggy', 'very foggy'],
};
